name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros-version: [foxy, rolling]
        include:
          - ros-version: foxy
            image: ros:foxy
          - ros-version: rolling
            image: ros:rolling
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Workspace
        run: |
          mkdir -p src_tmp/transport_drivers
          mv `find -maxdepth 1 -not -name . -not -name src_tmp` src_tmp/transport_drivers/
          mv src_tmp/ src/
      - name: Install Dependencies
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          apt-get update && rosdep update; \
          rosdep install --from-paths src --ignore-src -y'
      - name: Build Workspace
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon build --event-handlers console_cohesion+'
      - name: Run Tests
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon test --event-handlers console_cohesion+; \
          colcon test-result --verbose'
